name: CI

on:
  push:
    branches: [ master ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: seed-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Tests
#        run: |
#          cargo build --verbose
#          cargo test --verbose
      - name: Build image
        run: docker build -t $IMAGE_NAME .

      - name: Tag image latest
        run: |
          docker tag seed-api $DOCKER_USERNAME/$IMAGE_NAME:latest
          docker tag seed-api $DOCKER_USERNAME/$IMAGE_NAME:${{github.sha}}
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

      - name: push latest
        run: |
          docker push $DOCKER_USERNAME/$IMAGE_NAME:latest
          docker push $DOCKER_USERNAME/$IMAGE_NAME:${{github.sha}}
